version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: src/Web.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ASPNETCORE_URLS : ${ASPNETCORE_URLS}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Database: ${CONNECTION_STRING_DB}
    depends_on:
      - mssql

  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA_DB}
      SA_PASSWORD: ${SA_PASSWORD_DB}
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql
      
volumes:
  my-volume:
